PRAGMA foreign_keys=ON;
DROP TABLE IF EXISTS Product;

BEGIN TRANSACTION;
CREATE TABLE Product (
    PID INTEGER PRIMARY KEY AUTOINCREMENT,
    PCODE INTEGER NOT NULL,
    PBRAND TEXT NOT NULL CHECK(LENGTH(TRIM(PBRAND)) > 1),
    PNAME TEXT NOT NULL CHECK(LENGTH(TRIM(PNAME)) > 1),
    PTYPE TEXT NOT NULL CHECK(LENGTH(TRIM(PTYPE)) > 1),
    PUP FLOAT NOT NULL,
    PBP INTEGER NOT NULL,
    PQTY INTEGER NOT NULL
);
COMMIT TRANSACTION;