PRAGMA foreign_keys=ON;
DROP TABLE IF EXISTS Product;

BEGIN TRANSACTION;
CREATE TABLE Product (
    PID INTEGER PRIMARY KEY AUTOINCREMENT,
    PCODE INTEGER NOT NULL,
    PBRAND TEXT NOT NULL CHECK(LENGTH(TRIM(PBRAND)) > 1),
    PNAME TEXT NOT NULL CHECK(LENGTH(TRIM(PNAME)) > 1),
    PTYPE TEXT NOT NULL CHECK(LENGTH(TRIM(PTYPE)) > 1),
    PUP FLOAT NOT NULL,
    PBP INTEGER NOT NULL,
    PQTY INTEGER NOT NULL
);

INSERT INTO Product(PCODE,PBRAND,PNAME,PTYPE,PUP,PBP,PQTY)
VALUES (0053335521,"Sony","Playstation 5","Eletronic",499.99,399,1);

INSERT INTO Product(PCODE,PBRAND,PNAME,PTYPE,PUP,PBP,PQTY)
VALUES (0353335528,"KitKat","KitKat Cereal","Food & Drugs",19.99,10,0);

COMMIT TRANSACTION;